# SEO Values
title: Studio Pijin
tagline: My name is Pijin. I’m a washed up furry artist sometimes.
description: My name is Pijin. I’m a washed up furry artist sometimes.
url: https://github.com/StudioPijin
twitter: https://twitter.com/StudioPijin
logo: https://twitter.com/StudioPijin/photo

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  owner_name: Studio Pijin
  owner_url: https://github.com/StudioPijin

show_downloads: true
show_header: true
remote_theme: "dracula/gh-pages"
icon: icon_400.jpg

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
